create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  social_network text,
  social_handle text,
  rating int not null check (rating between 1 and 5),
  comment text not null,
  consent boolean not null default false,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists reviews_approved_created_idx on public.reviews (approved, created_at desc);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  path text,
  referrer text,
  language text,
  timezone text,
  screen text,
  device text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_idx on public.analytics_events (created_at desc);

alter table public.reviews enable row level security;
alter table public.analytics_events enable row level security;

-- La aplicación usa exclusivamente la service_role desde rutas de servidor.
-- No se crean políticas públicas para evitar exponer correos u otros datos internos.
